spring.application.name=auth-service
server.port=8086

# ==== JWT Configuration ====
jwt.secret=1bd60d58fd2ea08dbe372d41037ed595d366206a7b87c8bef1352145c280f8a7
jwt.expiration=3600000

# ==== Database Configuration ====
spring.datasource.url=jdbc:mysql://localhost:3306/rentahall?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==== JPA / Hibernate ====
# options: update / create / validate / none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect